title: "yzysimpleabs"
email: ""
description: "CS 背景产品经理个人主页。"
baseurl: ""
url: "https://yzysimpleabs.github.io"
remote_theme: samarsault/plainwhite-jekyll

lang: "zh-CN"
timezone: "Asia/Shanghai"

permalink: /:year/:month/:day/:title/
show_excerpts: false

markdown: kramdown
highlighter: rouge

kramdown:
  input: kramdown

author:
  name: "Zhiyuan Yang"
  bio: "CS 背景产品经理。"

plainwhite:
  name: "Zhiyuan Yang"
  tagline: "CS 背景产品经理"
  date_format: "%Y-%m-%d"
  html_lang: "zh-CN"
  search: false
  dark_mode: false
  condensed_mobile:
    - home
    - page
    - post
  social_links:
    github: yzysimpleabs

plugins:
  - jekyll-remote-theme
  - jekyll-feed
